# Generated by Django 4.1.2 on 2022-11-03 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('population', models.IntegerField(max_length=50)),
                ('area', models.IntegerField(max_length=40)),
                ('capiatal_city', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
