# Generated by Django 4.1.2 on 2022-10-29 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='desc',
            field=models.TextField(default=50, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination',
            name='image',
            field=models.ImageField(default=25, upload_to='pics'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination',
            name='name',
            field=models.CharField(default=20, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination',
            name='offer',
            field=models.BooleanField(default=False),
        ),
    ]
