# Generated by Django 4.1.2 on 2022-10-29 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0002_destination_desc_destination_image_destination_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
